
[credentials.usernames]

md.username = "Managing Director"
md.password = "$2b$12$xxxxxxxxxxxxxxxx"

hradmin.name = "HR/Admin"
hradmin.password = "$2b$12$xxxxxxxxxxxxxxxx"

pa.name = "Personal Assistant"
pa.password = "$2b$12$xxxxxxxxxxxxxxxx"

[cookie]
name = "hr_admin_system"
key = "some_random_secret_key"
expiry_days = 99999
